FROM python:3.10-slim

WORKDIR /app

# Install only what's needed for frontend
RUN pip install --no-cache-dir streamlit requests

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
